[versions]
agp = "8.12.3"
desugar_jdk_libsVersion = "2.1.5"
firebaseMessagingKtx = "24.1.2"
graalVmNative = "0.11.3"
jsPlainObjects = "2.3.0"
kfc = "16.5.0"
kiteui = "7.0.0-prerelease-113"
kotlin = "2.2.20"
kotlinerCli = "1.0.5"
kotlinxSerializationCsvDurable = "0.2.21-1"
ksp = "2.2.20-2.0.4"
lightningServer = "5.0.0-prerelease-322"
lightningServerKiteui = "8.0.0-prerelease-85"
serviceAbstractions = "0.0.1-131"
shadow = "8.1.1"

[libraries]
csvDurable = { module = "com.lightningkite:kotlinx-serialization-csv-durable", version = { ref = "kotlinxSerializationCsvDurable" } }
kiteui = { module = "com.lightningkite.kiteui:library", version = { ref = "kiteui" } }
lightningServer-core = { module = "com.lightningkite.lightningserver:core", version = { ref = "lightningServer" } }
lightningServer-core-shared = { module = "com.lightningkite.lightningserver:core-shared", version = { ref = "lightningServer" } }
lightningServer-engine-aws = { module = "com.lightningkite.lightningserver:engine-aws-serverless", version = { ref = "lightningServer" } }
lightningServer-secretSource-aws = { module = "com.lightningkite.lightningserver:secret-source-aws", version = { ref = "lightningServer" } }
lightningServer-engine-ktor = { module = "com.lightningkite.lightningserver:engine-ktor", version = { ref = "lightningServer" } }
lightningServer-engine-netty = { module = "com.lightningkite.lightningserver:engine-netty", version = { ref = "lightningServer" } }
lightningServer-files = { module = "com.lightningkite.lightningserver:files", version = { ref = "lightningServer" } }
lightningServer-files-shared = { module = "com.lightningkite.lightningserver:files-shared", version = { ref = "lightningServer" } }
lightningServer-media = { module = "com.lightningkite.lightningserver:media", version = { ref = "lightningServer" } }
lightningServer-media-shared = { module = "com.lightningkite.lightningserver:media-shared", version = { ref = "lightningServer" } }
lightningServer-sessions = { module = "com.lightningkite.lightningserver:sessions", version = { ref = "lightningServer" } }
lightningServer-sessions-email = { module = "com.lightningkite.lightningserver:sessions-email", version = { ref = "lightningServer" } }
lightningServer-sessions-shared = { module = "com.lightningkite.lightningserver:sessions-shared", version = { ref = "lightningServer" } }
lightningServer-sessions-sms = { module = "com.lightningkite.lightningserver:sessions-sms", version = { ref = "lightningServer" } }
lightningServer-typed = { module = "com.lightningkite.lightningserver:typed", version = { ref = "lightningServer" } }
lightningServer-typed-shared = { module = "com.lightningkite.lightningserver:typed-shared", version = { ref = "lightningServer" } }
lightningServer-client = { module = "com.lightningkite.lightningserver:client", version = { ref = "lightningServerKiteui" } }
lightningServer-client-serverUtils = { module = "com.lightningkite.lightningserver:server-client-utils", version = { ref = "lightningServerKiteui" } }
services-database = { module = "com.lightningkite.services:database", version = { ref = "serviceAbstractions" } }
services-database-jsonfile = { module = "com.lightningkite.services:database-jsonfile", version = { ref = "serviceAbstractions" } }
services-database-mongodb = { module = "com.lightningkite.services:database-mongodb", version = { ref = "serviceAbstractions" } }
services-database-processor = { module = "com.lightningkite.services:database-processor", version = { ref = "serviceAbstractions" } }
services-email-javasmtp = { module = "com.lightningkite.services:email-javasmtp", version = { ref = "serviceAbstractions" } }
services-files-s3 = { module = "com.lightningkite.services:files-s3", version = { ref = "serviceAbstractions" } }
services-notifications-firebase = { module = "com.lightningkite.services:notifications-fcm", version = { ref = "serviceAbstractions" } }
desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version = { ref = "desugar_jdk_libsVersion" } }
firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx", version = { ref = "firebaseMessagingKtx" } }
kotliner-cli = { module = "com.lightningkite:kotliner-cli", version = { ref = "kotlinerCli" } }

[plugins]
androidApp = { id = "com.android.application", version = { ref = "agp" } }
androidLibrary = { id = "com.android.library", version = { ref = "agp" } }
kiteui = { id = "com.lightningkite.kiteui", version = { ref = "kiteui" } }
graalVmNative = { id = "org.graalvm.buildtools.native", version = { ref = "graalVmNative" } }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version = { ref = "kotlin" } }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version = { ref = "kotlin" } }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version = { ref = "kotlin" } }
ksp = { id = "com.google.devtools.ksp", version = { ref = "ksp" } }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = { ref = "kotlin" } }
shadow = { id = "com.github.johnrengelman.shadow", version = { ref = "shadow" } }
kfc = { id = "io.github.turansky.kfc.application", version = { ref = "kfc" } }
kjsplain = { id = "org.jetbrains.kotlin.plugin.js-plain-objects", version = { ref = "jsPlainObjects" } }